include:
  - project: 'bitpowder/repo'
    ref: main
    file: '/.gitlab-ci-template.yml'

variables:
  DOCKER_DRIVER: overlay # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374
  GIT_DEPTH: "16"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  NAME: "clippy"

debian-bullseye-amd64:
  extends: .debian-bullseye-amd64

debian-bullseye-armhf:
  extends: .debian-bullseye-armhf-on-amd64

debian-bullseye-arm64:
  extends: .debian-bullseye-arm64-on-amd64

debian-bookworm-amd64:
  extends: .debian-bookworm-amd64

debian-bookworm-armhf:
  extends: .debian-bookworm-armhf-on-amd64

debian-bookworm-arm64:
  extends: .debian-bookworm-arm64-on-amd64

ubuntu-focal-amd64:
  extends: .ubuntu-focal-amd64

ubuntu-focal-arm64:
  extends: .ubuntu-focal-arm64-on-amd64

ubuntu-jammy-amd64:
  extends: .ubuntu-jammy-amd64

ubuntu-jammy-arm64:
  extends: .ubuntu-jammy-arm64-on-amd64

raspbian-bullseye-armhf:
  extends: .raspbian-bullseye-armhf

freebsd13-package-amd64:
  extends: .freebsd13-package-amd64

release:
  stage: deploy
  #only: stable
  tags: [freebsd-amd64-13]
  script:
  - curl --header 'Content-Type: application/json' --header "JOB-TOKEN: $CI_JOB_TOKEN" --data '{ "name": "Release v1.$CI_PIPELINE_IID", "tag_name": "v1.$CI_PIPELINE_IID", "description": "Automatic release from CI." }' --request POST "https://bitpowder.com:2443/api/v4/projects/68/releases"