include:
  - project: 'bitpowder/repo'
    ref: main
    file: '/.gitlab-ci-template.yml'

variables:
  DOCKER_DRIVER: overlay # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374
  GIT_DEPTH: "16"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  NAME: "clippy"

debian-buster-amd64:
  extends: .debian-buster-amd64

debian-buster-armhf:
  extends: .debian-buster-armhf-on-amd64

debian-buster-arm64:
  extends: .debian-buster-arm64-on-amd64

debian-bullseye-amd64:
  extends: .debian-bullseye-amd64

debian-bullseye-armhf:
  extends: .debian-bullseye-armhf-on-amd64

debian-bullseye-arm64:
  extends: .debian-bullseye-arm64-on-amd64

debian-bookworm-amd64:
  extends: .debian-bookworm-amd64

debian-bookworm-armhf:
  extends: .debian-bookworm-armhf-on-amd64

debian-bookworm-arm64:
  extends: .debian-bookworm-arm64-on-amd64

ubuntu-focal-amd64:
  extends: .ubuntu-focal-amd64

ubuntu-focal-arm64:
  extends: .ubuntu-focal-arm64-on-amd64

ubuntu-hirsute-amd64:
  extends: .ubuntu-hirsute-amd64

ubuntu-hirsute-arm64:
  extends: .ubuntu-hirsute-arm64-on-amd64

ubuntu-impish-amd64:
  extends: .ubuntu-impish-amd64

ubuntu-impish-arm64:
  extends: .ubuntu-impish-arm64-on-amd64

raspbian-buster-armhf:
  extends: .raspbian-buster-armhf

raspbian-bullseye-armhf:
  extends: .raspbian-bullseye-armhf

freebsd13-package-amd64:
  extends: .freebsd13-package-amd64

