include:
  - project: 'bitpowder/repo'
    ref: main
    file: '/.gitlab-ci-template.yml'

variables:
  DOCKER_DRIVER: overlay # faster docker builds, see https://gitlab.com/gitlab-org/gitlab-ce/issues/21374
  GIT_DEPTH: "16"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: "Release"
  PACKAGE_BUILD_OPTIONS: "-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=$BUILD_TYPE"
  BINARIES: "clippy-local clippy-remote"

debian-bullseye-amd64:
  extends: .debian-bullseye-amd64
  variables:
    PACKAGE: platform/packages-debian-bullseye/clippy
  script:
    - mkdir -p $PACKAGE/usr/bin build
    - cd build
    - cmake -G Ninja $DEB_PACKAGE_BUILD_OPTIONS -DCMAKE_INSTALL_PREFIX=../$PACKAGE/usr ..
    - cmake --build . --target install
    - find ../$PACKAGE

ubuntu-hirsute-amd64:
  extends: .ubuntu-hirsute-amd64
  variables:
    PACKAGE: platform/packages-ubuntu-hirsute/clippy
  script:
    - mkdir -p $PACKAGE/usr/bin build
    - cd build
    - cmake -G Ninja $PACKAGE_BUILD_OPTIONS -DCMAKE_INSTALL_PREFIX=../$PACKAGE ..
    - cmake --build . --target install
    - find ../$PACKAGE

raspbian-buster-armhf:
  extends: .raspbian-buster-armhf
  variables:
    PACKAGE: platform/packages-raspbian-buster/clippy
  script:
    - mkdir -p $PACKAGE/usr/bin build
    - cd build
    - cmake -G Ninja $PACKAGE_BUILD_OPTIONS -DCMAKE_INSTALL_PREFIX=../$PACKAGE ..
    - cmake --build . --target install
    - find ../$PACKAGE

freebsd13-package-amd64:
  stage: package
  needs: []
  dependencies: []
  only:
  - main 
  - stable 
  tags: [freebsd-amd64-13]
  script:
    - export ABI=`pkg -vv | grep -i '^abi' | cut -d'"' -f2`; echo $ABI
    - cmake -G Ninja $PACKAGE_BUILD_OPTIONS -DCMAKE_INSTALL_PREFIX=pkg/$ABI/usr/local .
    - cmake --build .
    - echo "cmake --build . --target install" | su
    - echo "cd pkg/$ABI; ../../platform/freebsd/build-pkg.sh ../../platform/freebsd/MANIFEST_TEMPLATE ../MANIFEST-$ABI ../../post-install ../../post-deinstall" | su
  after_script:
    - echo "chown -R gitlab-runner pkg" | su
  artifacts:
    expire_in: 1 day
    paths:
    - "pkg/*/*.pkg"
    - "pkg/MANIFEST-*"

